### ISSUE TITLE
[feature] experience-fragment support

### ISSUE THREAD

**Issue by niekraaijmakers** [adobe/aem-spa-project-core#25]
**Is your feature request related to a problem? Please describe.**
We want support for experience fragments in the SPA editor with as little code as possible.

**Describe the solution you'd like**
Resource type is provided.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by antoantonyk** [comment]
@niekraaijmakers #26  `/ui.apps/src/main/content/jcr_root/apps/spa-project-core/components/xf-page`, I think we need to add the body.html and update the content to include `<div id="spa-root"></div>` root element for spa right?

**Comment by niekraaijmakers** [comment]
@antoantonyk  lol you are totally right. how can I miss this. il add that in.

**Comment by niekraaijmakers** [comment]
@antoantonyk so actually with our current structure where extending "cq/experience-fragments/components/xfpage" is required, not optional, and given the rest of the code depends on the core component page, we cannot define those HTML files in here.

In the end the implementing project needs to define 3 files (customheaderlibs, customfooterlibs, body), but thats no big deal. If this PR would be accepted we can put it in the archetype.

**Comment by antoantonyk** [comment]
@niekraaijmakers oh ok.. actually I manually implement this feature in my project. Hope this will get merge soon. So I can eliminate few java model files.

**Comment by niekraaijmakers** [comment]
Yep. Thats the goal. The 3 HTML files aren't a big deal (for me at least :) ) but to get rid of these java models, would be nice.

**Comment by aula1011** [comment]
This looks really promising! Would be great to have OOTB support for experience fragments in the SPA editor.
Hope that it gets merged soon so that we can get rid of the workarounds currently in place.

Thanks @niekraaijmakers!

**Comment by niekraaijmakers** [comment]
@habansal ^^
