### ISSUE TITLE
aem-analyzer fails the build for a custom site using archetype 25 given there is a set version dependency and bundle start level which is not exporting[bug]

### ISSUE THREAD

**Issue by jaydubb12** [adobe/aem-spa-project-core#28]
**Describe the bug**
Site build fails when using Archetype 25, and the com.adobe.aem:spa.project.core is listed as a dependency.   The error message noted in the build console is below, and appears to be related to the utilization of the newer bnd-maven-plugin.

**Additional Info**
*This error appeared after the core component dependency was updated as outlined in the related ticket. 
*I looked through the pom.xml for both the custom site project based on archetype 25 and the SPA core project and could not find where this version dependency was being set, and tried a few options to set the values for the "Export-Package" as outlined in the plugin documentation, but was not able to get the error to subside, given I was getting a syntax error with respect to the entry to export the package via the bnd plugin...so anticipate my approach was wrong.

[ERROR] com.adobe.aem:spa.project.core.core:1.2.3-SNAPSHOT: Bundle spa.project.core.core:1.2.3-SNAPSHOT is importing package(s) Package com.adobe.cq.wcm.core.components.models;version=[12.18,13) in start level 20 but no visible bundle is exporting these for that start level in the required version range.

**Relates to**
https://github.com/adobe/aem-spa-project-core/issues/27

**Package version**
quickstart-6.5.7-p4502.jar
com.adobe.aem:spa.project.core.core:1.2.3-SNAPSHOT and com.adobe.aem:spa.project.core.core:1.2.0

**To Reproduce**
1. Create a project using Archetype 25 using the properties in the attachment
2. Build the SPA core project with the core component dependency set to 2.14.0 vs 2.11.1
3. Then build the custom site project, and note the error will appear when the aem-analyzer module is executed

**Expected behavior**
The aem-analyzer module would not produce an error / fail the build when the SPA Core Project is listed as a dependency

[archetype.properties.txt](https://github.com/adobe/aem-spa-project-core/files/6001565/archetype.properties.txt)

**Comment by pfauchere** [comment]
Internally tracked by CQ-4317712

**Comment by habansal** [comment]
This issue can be closed as no fix is required here. See explanation in https://github.com/adobe/aem-spa-project-core/issues/27
