### ISSUE TITLE
Build console displays warning that utf-8 not declared[bug]

### ISSUE THREAD

**Issue by jaydubb12** [adobe/aem-spa-project-core#29]
**Describe the bug**
When building the project, there is a warning that is displayed in the maven console that denotes that the utf-8 format is not explicitly declared

**Package version**
1.2.0
1.2.3-SNAPSHOT

**Remediation**
Append the following property to the all/pom.xml and the core/pom.xml
 <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

**Comment by pfauchere** [comment]
Internally tracked by CQ-4317712

**Comment by habansal** [comment]
Exact warning -
`[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!`
and
`[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!`

**Comment by habansal** [comment]
Fixed via https://github.com/adobe/aem-spa-project-core/pull/30 and released  spa.project.core-1.2.8
Closing this issue
