### ISSUE TITLE
[bug] Installing `spa.project.core.all` does not include bundle

### ISSUE THREAD

**Issue by ky940819** [adobe/aem-spa-project-core#5]
**Describe the bug**
When `spa.project.core.all` is installed, the bundle `com.adobe.aem:spa-project-core` is not installed.

This is because the filters for the `all` module overlap with the filters for the `ui.apps` module. 
Thus, the embedded bundle is installed when the `all` package is installed; but is immediately removed when the `ui.apps` sub-package is installed.

**Package version**
1.1.0

**To Reproduce**

- On a fresh AEM instance, install the `spa.project.core.all` package via the package manager.
- Note in the activity log the addition of the node `/apps/spa-project-core/install/spa.project.core.core-1.1.1-SNAPSHOT.jar`
- Note in further down in the activity log the deletion of the node `/apps/spa-project-core/install`
- Go to `/crx/de/index.jsp#/apps/spa-project-core/install/spa.project.core.core-1.1.1-SNAPSHOT.jar` and see that the node does not exist

**Expected behavior**
Expect the node `/apps/spa-project-core/install/spa.project.core.core-1.1.1-SNAPSHOT.jar` to exist after package install.

**Screenshot**
Screenshot of the package manager activity log upon installation on a fresh instace.
Deletion of newly added `install` folder is highlighted.
![Screenshot from 2020-09-13 23-22-00](https://user-images.githubusercontent.com/19987287/93037119-1595ac80-f618-11ea-988d-26ad6c2158c1.png)

**Comment by habansal** [comment]
New PR - https://github.com/adobe/aem-spa-project-core/pull/18
